language: python
python:
  - "3.6"
  - "3.7-dev"
# install dependencies
install:
  - pip install -r requirements.txt
# run tests
script:
  - python migrate.py
  - python -W ignore -m unittest discover -vv -s tests -p "*test.py"