apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mbtaccess-deployment
  annotations:
  labels:
    app: mbtaccess
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mbtaccess
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbtaccess
    spec:
      containers:
      - image: gcr.io/mbtaccess/github-growwithgooglema-mbtaccess:master
        imagePullPolicy: Always
        name: github-growwithgooglema-mbtaccess
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
